title: Kenis
author: Kenis
language: zh-CN
timezone: Asia/Shanghai
url: https://kenis1108.github.io
root: /
permalink: posts/:abbrlink.html
skip_render: 
  - "live2d-widget/**/*"
  - "myhtml/**"
meta_generator: true
theme: butterfly

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true


