services:
  hexo:
    image: node:latest
    container_name: hexo-site
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    tty: true
    stdin_open: true