name: Deploy VitePress To GitHub Pages

on:
  push:
    branches:
      - vitepress # 当vitepress分支有推送时触发

# 添加权限设置
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Node.js版本
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .vitepress/dist # 构建产物目录
          branch: vitepress-gh-pages # 部署到vitepress-gh-pages分支
          clean: true # 清理目标分支
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Deploy from ${{ github.event.head_commit.message }} (Commit: ${{ github.sha }}, Time: ${{ github.event.head_commit.timestamp }})"
